name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw --batch-mode verify
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-keep
          path: |
            target/faker-**.jar
      - name: Configure settings key
        run: |
          mkdir -p ~/.m2
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><settings xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd\" xmlns=\"http://maven.apache.org/SETTINGS/1.1.0\"
            xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><servers><server><id>github</id><username>Tcharl</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Publish package
        run: ./mvnw --batch-mode deploy -s ~/.m2/settings.xml
